
###  Criar Banco 
POST http://localhost:3333/api/banks
Content-Type: application/json

{
  "name": "Banco Inter"
}

#######################################

#Listar os Bancos 
GET http://localhost:3333/api/banks

#######################################
# Atualizar Banco 
PUT http://localhost:3333/api/banks/47d487d6-a6c7-4bfd-bc29-9bdb48325143
Content-Type: application/json

{
  "name": "Banco Inter S.A."
}

#######################################
# Deletar Banco
DELETE http://localhost:3333/api/banks/d0c09913-764d-4e5b-b23a-f0e597212e43

#######################################

### Criar Categoria
POST http://localhost:3333/api/categories
Content-Type: application/json

{
  "name": "Moradia",
  "icon": "Home"
}

#######################################
# Listar Categoria 
GET http://localhost:3333/api/categories

#######################################
# Atualizar Categoria
PUT http://localhost:3333/api/categories/672f7887-228a-44cb-803c-854dd705f35b
Content-Type: application/json

{
  "name": "Contas de Casa",
  "icon": "Home"
}

#######################################
# Deletar Categoria
DELETE http://localhost:3333/api/categories/d236dd73-111a-4a0f-8154-7c68dea80a2a

####################################### 

# Criar Transação
POST http://localhost:3333/api/transactions
Content-Type: application/json

{
  "description": "Aluguel",
  "amount": 1800.50,
  "type": "expense",
  "bankId": "47d487d6-a6c7-4bfd-bc29-9bdb48325143",
  "categoryId": "672f7887-228a-44cb-803c-854dd705f35b"
}


#######################################
# Buscar transação
GET http://localhost:3333/api/transactions/f5f0c3f3-0951-43e9-8e7f-8929199f2fdf

#######################################
# Atualizar Transação 
PUT http://localhost:3333/api/transactions/f5f0c3f3-0951-43e9-8e7f-8929199f2fdf
Content-Type: application/json

{
  "description": "Aluguel Atualizado",
  "amount": 1850.00
}

#######################################
# Deletar transação 
DELETE http://localhost:3333/api/transactions/f5f0c3f3-0951-43e9-8e7f-8929199f2fdf